A consumer is just a construct that makes use of our messages and performs an action once a message is received. You
could view a consumer as a "user of messages". Since we have integrated the `rabbitmq-native` plugin this provides us
with a new command to easily create consumers. In your terminal go ahead and execute the following.

[source,bash]
----
$ grails create-consumer demo.Test
----

This will create a new folder under your `grails-app` called `rabbit-consumers`. In your `rabbit-consumers` folder there
will now be a file called `TestConsumer`.

[source,groovy]
.grails-app/rabbit-consumers/demo/TestConsumer.groovy
----
package demo

import com.budjb.rabbitmq.consumer.MessageContext

class TestConsumer {

    static rabbitConfig = [
        : // TODO: Setup config.
    ]

    /**
     * Handle an incoming RabbitMQ message.
     *
     * @param body    The converted body of the incoming message.
     * @param context Properties of the incoming message.
     * @return
     */
    def handleMessage(def body, MessageContext messageContext) {
        // TODO: Handle messages
        body
    }
}
----

Now we need to connect our consumer to the message queue. To do that update the `rabbitConfig` block as follows.

[source,groovy]
.grails-app/rabbit-consumers/demo/TestConsumer.groovy
----
include::{sourceDir}/grails-app/rabbit-consumers/demo/TestConsumer.groovy[indent=0, tag=connectRabbit1]
----

Now that the consumer knows where to look for messages we need to tell it what to do once it receives a message. In this
case we just return the string 'Hello to you, too!'.

[source,groovy]
.grails-app/rabbit-consumers/demo/TestConsumer.groovy
----
include::{sourceDir}/grails-app/rabbit-consumers/demo/TestConsumer.groovy[indent=0, tag=handleMessage1]
----

WARNING: Look carefully at the handleMessage arguments. The `create-consumer` creates `handleMessage` with a argument of
`def body`, in our example we have typed it as a `String` rather than `def`. This is due to when defining body using def
the incoming body is always null and you never receive your message. We recommend typing your arguments when handling
incoming messages.