With our dependencies added, we need to configure security.
Create a file `application.groovy` with the following content:

[source,groovy]
.grails-app/conf/application.groovy
----
include::{sourceDir}/grails-app/conf/application.groovy[indent=0]
----
<1> Secure the token storage. The secret can be set to any value.
<2> Callback url, after selecting your google user this is where Google will attempt to return with your authentication token
<3> Which pac4j client to use; in our case the Google client
<4> Open your `client_id.json` you downloaded while setting up Google and insert your `client_id` field as your key
<5> Open your `client_id.json` you downloaded while setting up Google and insert your `client_secret` as your secret
<6> The scope can be from any value of the enum org.pac4j.oauth.client.Google2Client.Google2Scope
<7> Specific roles that Google authentication is allowed to access
<8> We are going to authenticate our users only against Google. Thus, we use only the anonymous authentication provider. Read more about https://grails-plugins.github.io/grails-spring-security-core/latest/#authenticationProviders[Authentication Providers] in Spring Security Core Plugin documentation.

WARNING: While the scope can be from any value of the enum org.pac4j.oauth.client.Google2Client.Google2Scope, if you use
the default OauthUserDetailsService, you need to use EMAIL_AND_PROFILE. That is because the default implementation uses
the profile ID as the username, and that is only returned by Google if EMAIL_AND_PROFILE scope is used.

NOTE: We are not persisting User information in the database. You may have noticed we don't have `User`, `Role`, `UserRole` domain classes in the project. Neither we setup configuration values such as `userLookUp.userDomainClass` etc.

Now we override the `login/auth` view. So that we no longer show a username/password form in that page.


[source,groovy]
.grails-app/views/login/auth.gsp
----
include::{sourceDir}/grails-app/views/login/auth.gsp[indent=0]
----

We don't include a button to SignIn with Google in that page because we have included that button in root layout _main.gsp_ file.
