With our dependencies added and our basic security config now in place we can go ahead and add our OAuth2 configuration.
In our `application.groovy` go ahead and add the following block.

[source,groovy]
.grails-app/conf/application.groovy
----
include::{sourceDir}/grails-app/conf/application.groovy[indent=0, tag=oauthConfig]
----
<1> Callback url, after selecting your google user this is where Google will attempt to return with your authentication token
<2> Which pac4j client to use; in our case the Google client
<3> Open your `client_id.json` you downloaded while setting up Google and insert your `client_id` field as your key
<4> Open your `client_id.json` you downloaded while setting up Google and insert your `client_secret` as your secret
<5> The scope can be from any value of the enum org.pac4j.oauth.client.Google2Client.Google2Scope
<6> Specific roles that Google authentication is allowed to access

WARNING: While the scope can be from any value of the enum org.pac4j.oauth.client.Google2Client.Google2Scope, if you use
the default OauthUserDetailsService, you need to use EMAIL_AND_PROFILE. That is because the default implementation uses
the profile ID as the username, and that is only returned by Google if EMAIL_AND_PROFILE scope is used.

Now that we have all our OAuth2 configuration in place lets go ahead and put the rest of our app together.